name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        required: false
        description: The name of artifact files
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying and uploading..."